# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models.
name: 'globalmart'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# Paths configuration for different types of files
# dbt will look for models, analyses, tests, seeds, macros, and snapshots
model-paths: ["models"]      # Directory for models
analysis-paths: ["analyses"] # Directory for analyses
test-paths: ["tests"]        # Directory for tests
seed-paths: ["seeds"]        # Directory for seed data
macro-paths: ["macros"]      # Directory for macros
snapshot-paths: ["snapshots"] # Directory for snapshots

target-path: "target"        # Directory to store compiled SQL files
clean-targets:               # Directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Default materialization for models is a view. The configuration below overrides
# this setting for specific folders. Models in the root of the models folder
# will continue to be built as views unless specified otherwise.

models:
  globalmart:
    raw:
      +materialized: table     # Materialize raw models as tables
    staging:
      +materialized: view       # Materialize staging models as views
    reporting:
      +materialized: table      # Materialize reporting models as tables